chiliz/doctrine-bundle:
  v1.0:
    bundles:
      Chiliz\DoctrineBundle\ChilizDoctrineBundle: ['all']
    copyFromRecipe:
      - config/packages/chiliz_doctrine.yaml
  v1.2:
    bundles:
      Chiliz\DoctrineBundle\ChilizDoctrineBundle: ['all']
    copyFromRecipe:
      - config/packages/chiliz_doctrine.yaml
      - bin/post-release-migration
      - bin/pre-release-migration
    makefile:
      - "-include vendor/chiliz/doctrine-bundle/make/doctrine.mk"