chiliz/code-quality:
  v1.0:
    gitignore:
      - .php-cs-fixer.cache
      - .phpcs-cache
    copyFromRecipe:
      - .editorconfig
      - .php-cs-fixer.dist.php
      - phpcs.xml.dist
      - phpmd.xml
      - phpstan.neon
      - rector.php
    makefile:
      - "-include vendor/chiliz/code-quality/make/code_quality.mk"
  v1.4:
    gitignore:
      - .php-cs-fixer.cache
      - .phpcs-cache
    copyFromRecipe:
      - .editorconfig
      - .php-cs-fixer.dist.php
      - phpcs.xml.dist
      - phpmd.xml
      - phpstan.neon
      - rector.php
    makefile:
      - "-include vendor/chiliz/code-quality/make/code_quality.mk"
    composerCommands:
        "[ $COMPOSER_DEV_MODE -eq 0 ] ||  (mkdir -p .gitlab/merge_request_templates && cp vendor/chiliz/code-quality/.gitlab/merge_request_templates/Default.md .gitlab/merge_request_templates)": "script"
  v2.0:
    gitignore:
      - .php-cs-fixer.cache
      - .phpcs-cache
    copyFromRecipe:
      - .editorconfig
      - .php-cs-fixer.dist.php
      - phpcs.xml.dist
      - phpmd.xml
      - phpstan.neon
      - rector.php
      - gherkinlint.json
    makefile:
      - "-include vendor/chiliz/code-quality/make/code_quality.mk"
    composerCommands:
      "[ $COMPOSER_DEV_MODE -eq 0 ] ||  (mkdir -p .gitlab/merge_request_templates && cp vendor/chiliz/code-quality/.gitlab/merge_request_templates/Default.md .gitlab/merge_request_templates)": "script"
  v2.1:
    gitignore:
      - .php-cs-fixer.cache
      - .phpcs-cache
    copyFromRecipe:
      - .editorconfig
      - .php-cs-fixer.dist.php
      - phpcs.xml.dist
      - phpmd.xml
      - phpstan.neon
      - rector.php
      - gherkinlint.json
      - renovate.json
    makefile:
      - "-include vendor/chiliz/code-quality/make/code_quality.mk"
    composerCommands:
      "[ $COMPOSER_DEV_MODE -eq 0 ] ||  (mkdir -p .gitlab/merge_request_templates && cp vendor/chiliz/code-quality/.gitlab/merge_request_templates/Default.md .gitlab/merge_request_templates)": "script"
  v2.9:
    bundles:
      Chiliz\CodeQuality\ChilizCodeQualityBundle: [ 'dev' ]
    gitignore:
      - .php-cs-fixer.cache
      - .phpcs-cache
    copyFromRecipe:
      - .editorconfig
      - .php-cs-fixer.dist.php
      - phpcs.xml.dist
      - phpmd.xml
      - phpstan.neon
      - rector.php
      - gherkinlint.json
      - renovate.json
    makefile:
      - "-include vendor/chiliz/code-quality/make/code_quality.mk"
    composerCommands:
      "[ $COMPOSER_DEV_MODE -eq 0 ] ||  (mkdir -p .gitlab/merge_request_templates && cp vendor/chiliz/code-quality/.gitlab/merge_request_templates/Default.md .gitlab/merge_request_templates)": "script"
  v2.11:
    bundles:
      Chiliz\CodeQuality\ChilizCodeQualityBundle: [ 'dev' ]
    gitignore:
      - .php-cs-fixer.cache
      - .phpcs-cache
    copyFromRecipe:
      - .editorconfig
      - .php-cs-fixer.dist.php
      - phpcs.xml.dist
      - phpmd.xml
      - phpstan.neon
      - rector.php
      - gherkinlint.json
      - renovate.json
    makefile:
      - "-include vendor/chiliz/code-quality/make/code_quality.mk"
    composerCommands:
      "[ $COMPOSER_DEV_MODE -eq 0 ] ||  (mkdir -p .gitlab/merge_request_templates && cp vendor/chiliz/code-quality/.gitlab/merge_request_templates/Default.md .gitlab/merge_request_templates)": "script"
