chiliz/gitlab-api-client-bundle:
  v1.0:
    bundles:
      Chiliz\GitlabApiBundle\GitlabApiBundle: ['all']
    copyFromRecipe:
      - config/packages/chiliz_gitlab_api.yaml
    envs:
      GITLAB_API_BASE_URL: ''
      GITLAB_API_TOKEN: ''