chiliz/jira-api-client-bundle:
  v1.0:
    bundles:
      Chiliz\JiraApiBundle\JiraApiBundle: ['all']
    copyFromRecipe:
      - config/packages/chiliz_jira_api.yaml
    envs:
      JIRA_BASE_URL: ''
      JIRA_USER_EMAIL: ''
      JIRA_USER_TOKEN: ''