chiliz/service-clients-bundle:
  v1.0:
    bundles:
      Chiliz\ServiceClientsBundle\ChilizServiceClientsBundle: ['all']
    envs:
      "#1": "Endpoint configuration for Chilipay Api Proxy"
      CHILIPAY_API_PROXY_BASE_URL: ''
      CHILIPAY_API_PROXY_CONSUMER_NAME: ''
      CHILIPAY_API_PROXY_CONSUMER_KEY: ''
      "#2": "Endpoint configuration for Chiliz Api Proxy"
      CHILIZ_API_PROXY_BASE_URL: ''
      CHILIZ_API_PROXY_CONSUMER_NAME: ''
      CHILIZ_API_PROXY_CONSUMER_KEY: ''
    copyFromRecipe:
      - config/packages/chiliz_service_clients.yaml
      - config/packages/test/chiliz_service_clients.yaml
