chiliz_utilities_bundle:
    global:
        serviceName: '%service_name%'
    cache :
        enabled : true
        redisDsn : '%env(string:REDIS_CLUSTER_DSN)%'
    encryption:
        enabled: true
        salt: '%env(string:SALT_KEY)%'
        key: '%env(string:ENCRYPTION_KEY)%'
        entityManager: '@doctrine.orm.entity_manager'
        entityConfiguration:

    swagger:
        enabled: true
    paramConverters:
        enabled: true
    serializer:
        enabled: true
    concurrency:
        enabled: true
    referenceNumber:
        enabled: true
    response:
        enabled: true
    pagination:
        enabled: true
    context:
        enabled: true
    exceptionHandler:
        enabled: true
    remainingLimits:
        enabled: true
    locale:
        enabled: true
    lock:
        enabled: true
    notifications:
        enabled: true
    imageService:
        enabled: true
        listImagesServiceClient: 'service_client.service.shared.image.list_images'
        throttleBatchNumber: '%maxImageEntities%'
        imageRetriever: 'Chiliz\ServiceClientsBundle\ImageService\ListImagesServiceClient'
    transformRequest:
        enabled: true
    userCredential:
        enabled: true
        retriever: Chiliz\ServiceClientsBundle\Services\Shared\User\Credentials\RetrieveUserCredentialContext
    userLocation:
        enabled: true
    timestampListener:
        enabled: true
    sentry:
        enabled: true
        sensitiveKeys: []
    sns:
        enabled: false
    sqs:
        enabled: true
    daemonLifecycle:
        enabled: true
        projectRootDir: '%kernel.project_dir%'
    monitoringController:
        enabled: true
    clientIp:
        enabled: true
    slaveRepository:
        enabled: true
    client:
        enabled: true
